"""
process_data.py
===============
ETL Cleaning Pipeline — Medical Research Data Migration Platform

PURPOSE:
    Reads the 5 raw CSV files generated by generate_data.py, applies a series
    of data quality transformations, and writes 5 cleaned CSVs to Data/processed/.

    This script represents the "T" (Transform) step in the ETL pipeline.
    A BA designed these rules by analysing the source data and interviewing
    the research staff who originally entered it.

TRANSFORMATIONS APPLIED:
    1. Parse & standardise dates    — 3 inconsistent formats → YYYY-MM-DD
    2. Normalise boolean fields     — Yes/Y/1/True/TRUE → True | No/N/0/False → False
    3. Clean currency strings       — "$2,450.00" → 2450.0 (float)
    4. Standardise gender values    — MALE/male/M → Male
    5. Remove duplicate records     — deduplicate by primary key
    6. Drop critical nulls          — remove rows missing non-nullable fields
    7. Trim whitespace              — strip leading/trailing spaces from strings

HOW TO RUN:
    python process_data.py

PREREQUISITES:
    Run generate_data.py first to populate Data/raw/ with source files.

INPUT:
    Data/raw/researchers.csv
    Data/raw/studies.csv
    Data/raw/participants.csv
    Data/raw/outcomes.csv
    Data/raw/biosamples.csv

OUTPUT:
    Data/processed/researchers.csv
    Data/processed/studies.csv
    Data/processed/participants.csv
    Data/processed/outcomes.csv
    Data/processed/biosamples.csv

Author: Maria Trinidad Edwards
"""

import pandas as pd
import numpy as np
import os
import re
from datetime import datetime

# ── Directory paths ────────────────────────────────────────────────────────────
INPUT_DIR  = "Data/raw"
OUTPUT_DIR = "Data/processed"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("🧹 Medical Research ETL Cleaning Pipeline")
print("=" * 55)
print(f"   Input  : {INPUT_DIR}/")
print(f"   Output : {OUTPUT_DIR}/")
print(f"   Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")


# ─────────────────────────────────────────────────────────────────────────────
# TRANSFORMATION FUNCTIONS
# Each function handles one specific data quality problem.
# Keeping them separate makes it easy to test, reuse, and explain.
# ─────────────────────────────────────────────────────────────────────────────

def parse_date(value):
    """
    Parse a date string into ISO format (YYYY-MM-DD), handling 3 known formats.

    WHY THREE FORMATS:
        - %Y-%m-%d  e.g. "2023-05-20"  — ISO standard (most modern systems)
        - %d/%m/%Y  e.g. "20/05/2023"  — common in Australian clinical settings
        - %b-%d-%Y  e.g. "May-20-2023" — US abbreviated month (imported data)

    Returns:
        str  — cleaned date as "YYYY-MM-DD"
        None — if the value is missing or unparseable
    """
    if pd.isna(value) or str(value).strip() == "":
        return None

    value = str(value).strip()

    date_formats = [
        "%Y-%m-%d",    # ISO: 2023-05-20
        "%d/%m/%Y",    # Australian: 20/05/2023
        "%b-%d-%Y",    # US abbreviated: May-20-2023
    ]

    for fmt in date_formats:
        try:
            return datetime.strptime(value, fmt).strftime("%Y-%m-%d")
        except ValueError:
            continue

    # If none of the formats matched, log a warning and return None
    print(f"   ⚠️  Unparseable date: '{value}' — set to null")
    return None


def parse_bool(value):
    """
    Normalise any boolean-like value to Python True or False.

    Handles all variants produced by generate_data.py:
        True  ← "Yes", "Y", "1", "True", "TRUE", True
        False ← "No", "N", "0", "False", "FALSE", False

    Returns:
        bool  — True or False
        None  — if the value is missing
    """
    if pd.isna(value):
        return None

    # Already a Python bool
    if isinstance(value, bool):
        return value

    # Numeric: 1 → True, 0 → False
    if isinstance(value, (int, float)):
        return bool(int(value))

    true_values  = {"yes", "y", "1", "true"}
    false_values = {"no",  "n", "0", "false"}

    normalised = str(value).strip().lower()

    if normalised in true_values:
        return True
    if normalised in false_values:
        return False

    print(f"   ⚠️  Unparseable boolean: '{value}' — set to null")
    return None


def parse_currency(value):
    """
    Convert a currency string like "$2,450.00" to a float 2450.0.

    Steps:
        1. Strip the "$" sign
        2. Remove comma thousands separators
        3. Convert to float

    Returns:
        float — the numeric value
        None  — if the value is missing or unparseable
    """
    if pd.isna(value) or str(value).strip() == "":
        return None

    try:
        cleaned = re.sub(r"[$,]", "", str(value).strip())
        return float(cleaned)
    except ValueError:
        print(f"   ⚠️  Unparseable currency: '{value}' — set to null")
        return None


def normalise_gender(value):
    """
    Standardise gender to one of three canonical values.

    Mapping:
        "Male"       ← "Male", "MALE", "male", "M", "m"
        "Female"     ← "Female", "FEMALE", "female", "F", "f"
        "Non-binary" ← "Non-binary", "NB", "non-binary", "Other"

    Returns:
        str  — "Male", "Female", or "Non-binary"
        None — if the value is missing
    """
    if pd.isna(value):
        return None

    male_variants       = {"male", "m"}
    female_variants     = {"female", "f"}
    nonbinary_variants  = {"non-binary", "nb", "other"}

    normalised = str(value).strip().lower()

    if normalised in male_variants:
        return "Male"
    if normalised in female_variants:
        return "Female"
    if normalised in nonbinary_variants:
        return "Non-binary"

    print(f"   ⚠️  Unrecognised gender: '{value}' — set to null")
    return None


def trim_strings(df):
    """
    Strip leading and trailing whitespace from all string columns.

    WHY: Whitespace is invisible and causes unexpected comparison failures.
    "Male " != "Male" — this breaks filtering, grouping, and joins.
    """
    str_cols = df.select_dtypes(include="object").columns
    for col in str_cols:
        df[col] = df[col].apply(
            lambda x: x.strip() if isinstance(x, str) else x
        )
    return df


# ─────────────────────────────────────────────────────────────────────────────
# REPORTING HELPER
# ─────────────────────────────────────────────────────────────────────────────

def report(label, before, after, extra=""):
    """Print a one-line summary of what was removed or changed."""
    removed = before - after
    pct     = (removed / before * 100) if before > 0 else 0
    tag     = f"  → removed {removed:,} rows ({pct:.1f}%)" if removed > 0 else "  → no rows removed"
    print(f"   {label}: {before:,} → {after:,}{tag}{extra}")


# ─────────────────────────────────────────────────────────────────────────────
# DATASET CLEANERS
# One function per dataset — each knows the specific columns to transform.
# ─────────────────────────────────────────────────────────────────────────────

def clean_researchers(path_in, path_out):
    print("\n📋 Cleaning: researchers.csv")
    df = pd.read_csv(path_in)
    n_raw = len(df)

    # Step 1 — Trim whitespace
    df = trim_strings(df)

    # Step 2 — Remove exact duplicates (same researcher_id = duplicate import)
    before = len(df)
    df = df.drop_duplicates(subset=["researcher_id"])
    report("Deduplication (researcher_id)", before, len(df))

    # Step 3 — Parse dates
    df["hire_date"] = df["hire_date"].apply(parse_date)

    # Step 4 — Normalise boolean
    df["is_active"] = df["is_active"].apply(parse_bool)

    # Step 5 — Drop rows missing critical non-nullable fields
    before = len(df)
    df = df.dropna(subset=["researcher_id", "last_name", "department"])
    report("Drop critical nulls", before, len(df))

    df.to_csv(path_out, index=False)
    print(f"   ✅ {n_raw:,} raw → {len(df):,} clean rows saved")
    return df


def clean_studies(path_in, path_out):
    print("\n🔬 Cleaning: studies.csv")
    df = pd.read_csv(path_in)
    n_raw = len(df)

    # Step 1 — Trim whitespace
    df = trim_strings(df)

    # Step 2 — Remove exact duplicates
    before = len(df)
    df = df.drop_duplicates(subset=["study_id"])
    report("Deduplication (study_id)", before, len(df))

    # Step 3 — Parse dates
    df["start_date"] = df["start_date"].apply(parse_date)
    df["end_date"]   = df["end_date"].apply(parse_date)

    # Step 4 — Normalise boolean
    df["ethics_approved"] = df["ethics_approved"].apply(parse_bool)

    # Step 5 — Clean currency
    df["budget_aud"] = df["budget_aud"].apply(parse_currency)

    # Step 6 — Drop rows missing critical fields
    before = len(df)
    df = df.dropna(subset=["study_id", "title", "principal_researcher", "start_date"])
    report("Drop critical nulls", before, len(df))

    # Step 7 — Validate: end_date should be after start_date
    before = len(df)
    mask_invalid = (
        df["end_date"].notna() &
        (df["end_date"] < df["start_date"])
    )
    df.loc[mask_invalid, "end_date"] = None   # Null out invalid end dates
    if mask_invalid.sum() > 0:
        print(f"   ⚠️  {mask_invalid.sum()} end_date values were before start_date — set to null")

    df.to_csv(path_out, index=False)
    print(f"   ✅ {n_raw:,} raw → {len(df):,} clean rows saved")
    return df


def clean_participants(path_in, path_out):
    print("\n👥 Cleaning: participants.csv")
    df = pd.read_csv(path_in)
    n_raw = len(df)

    # Step 1 — Trim whitespace
    df = trim_strings(df)

    # Step 2 — Remove exact duplicates
    before = len(df)
    df = df.drop_duplicates(subset=["participant_id"])
    report("Deduplication (participant_id)", before, len(df))

    # Step 3 — Parse dates
    df["enrolment_date"] = df["enrolment_date"].apply(parse_date)

    # Step 4 — Normalise booleans
    df["consent_given"] = df["consent_given"].apply(parse_bool)
    df["withdrawn"]     = df["withdrawn"].apply(parse_bool)

    # Step 5 — Normalise gender
    df["gender"] = df["gender"].apply(normalise_gender)

    # Step 6 — Validate age range (18–120 is the realistic range for research)
    before = len(df)
    invalid_age = df["age"].notna() & ~df["age"].between(18, 120)
    df.loc[invalid_age, "age"] = None
    if invalid_age.sum() > 0:
        print(f"   ⚠️  {invalid_age.sum()} age values outside 18–120 — set to null")

    # Step 7 — Drop rows missing critical fields
    before = len(df)
    df = df.dropna(subset=["participant_id", "study_id", "enrolment_date"])
    report("Drop critical nulls", before, len(df))

    # Step 8 — Ensure participants without consent are flagged
    # (Business rule: consent_given must be True for active participants)
    no_consent = df["consent_given"] == False
    if no_consent.sum() > 0:
        print(f"   ℹ️  {no_consent.sum()} participants flagged as consent_given=False — retained but flagged")

    df.to_csv(path_out, index=False)
    print(f"   ✅ {n_raw:,} raw → {len(df):,} clean rows saved")
    return df


def clean_outcomes(path_in, path_out):
    print("\n📊 Cleaning: outcomes.csv")
    df = pd.read_csv(path_in)
    n_raw = len(df)

    # Step 1 — Trim whitespace
    df = trim_strings(df)

    # Step 2 — Remove exact duplicates
    before = len(df)
    df = df.drop_duplicates(subset=["outcome_id"])
    report("Deduplication (outcome_id)", before, len(df))

    # Step 3 — Parse dates
    df["measurement_date"] = df["measurement_date"].apply(parse_date)

    # Step 4 — Normalise boolean
    df["within_normal_range"] = df["within_normal_range"].apply(parse_bool)

    # Step 5 — Validate numeric value (must be positive)
    before = len(df)
    invalid_value = df["value"].notna() & (df["value"] < 0)
    df.loc[invalid_value, "value"] = None
    if invalid_value.sum() > 0:
        print(f"   ⚠️  {invalid_value.sum()} negative measurement values — set to null")

    # Step 6 — Drop rows missing critical fields
    before = len(df)
    df = df.dropna(subset=["outcome_id", "participant_id", "measurement_type", "measurement_date"])
    report("Drop critical nulls", before, len(df))

    df.to_csv(path_out, index=False)
    print(f"   ✅ {n_raw:,} raw → {len(df):,} clean rows saved")
    return df


def clean_biosamples(path_in, path_out):
    print("\n🧪 Cleaning: biosamples.csv")
    df = pd.read_csv(path_in)
    n_raw = len(df)

    # Step 1 — Trim whitespace
    df = trim_strings(df)

    # Step 2 — Remove exact duplicates
    before = len(df)
    df = df.drop_duplicates(subset=["biosample_id"])
    report("Deduplication (biosample_id)", before, len(df))

    # Step 3 — Parse dates
    df["collection_date"] = df["collection_date"].apply(parse_date)

    # Step 4 — Clean currency (processing cost)
    df["processing_cost"] = df["processing_cost"].apply(parse_currency)

    # Step 5 — Normalise boolean
    df["is_viable"] = df["is_viable"].apply(parse_bool)

    # Step 6 — Validate volume (must be positive)
    invalid_vol = df["volume_ml"].notna() & (df["volume_ml"] <= 0)
    df.loc[invalid_vol, "volume_ml"] = None
    if invalid_vol.sum() > 0:
        print(f"   ⚠️  {invalid_vol.sum()} non-positive volume_ml values — set to null")

    # Step 7 — Drop rows missing critical fields
    before = len(df)
    df = df.dropna(subset=["biosample_id", "participant_id", "sample_type", "collection_date"])
    report("Drop critical nulls", before, len(df))

    df.to_csv(path_out, index=False)
    print(f"   ✅ {n_raw:,} raw → {len(df):,} clean rows saved")
    return df


# ─────────────────────────────────────────────────────────────────────────────
# MAIN — Run all cleaners in order
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # Check that raw data exists
    required_files = [
        "researchers.csv", "studies.csv", "participants.csv",
        "outcomes.csv", "biosamples.csv"
    ]
    missing = [f for f in required_files if not os.path.exists(f"{INPUT_DIR}/{f}")]
    if missing:
        print(f"\n❌ Missing raw files: {missing}")
        print(f"   Run generate_data.py first to create them.")
        exit(1)

    # Run each cleaner
    researchers  = clean_researchers(
        f"{INPUT_DIR}/researchers.csv",
        f"{OUTPUT_DIR}/researchers.csv"
    )
    studies      = clean_studies(
        f"{INPUT_DIR}/studies.csv",
        f"{OUTPUT_DIR}/studies.csv"
    )
    participants = clean_participants(
        f"{INPUT_DIR}/participants.csv",
        f"{OUTPUT_DIR}/participants.csv"
    )
    outcomes     = clean_outcomes(
        f"{INPUT_DIR}/outcomes.csv",
        f"{OUTPUT_DIR}/outcomes.csv"
    )
    biosamples   = clean_biosamples(
        f"{INPUT_DIR}/biosamples.csv",
        f"{OUTPUT_DIR}/biosamples.csv"
    )

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\n" + "=" * 55)
    print("✅ ETL Pipeline Complete!")
    print(f"   Finished: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"\n   📁 Clean files saved to: {OUTPUT_DIR}/")
    print(f"\n   📊 Final record counts:")
    print(f"      Researchers : {len(researchers):,}")
    print(f"      Studies     : {len(studies):,}")
    print(f"      Participants: {len(participants):,}")
    print(f"      Outcomes    : {len(outcomes):,}")
    print(f"      Biosamples  : {len(biosamples):,}")
    total = len(researchers) + len(studies) + len(participants) + len(outcomes) + len(biosamples)
    print(f"      TOTAL       : {total:,}")
    print("\n   ✅ Data is now ready to load into PostgreSQL (run load_data.py)")
